on:
  release:
    types:
      - created
name: Generate artifacts v7
jobs:
  generate-artifacts:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Get current tag
        uses: olegtarasov/get-tag@v2
        id: tag_name
      - name: Ensure up-to-date apt packages and lists
        run: |
          sudo apt-get update
          sudo apt-get upgrade
      - name: Install dependencies
        run: sudo apt-get install -y help2man python3-setuptools
      - name: Install Python wheel package
        run: pip3 install wheel
      - name: Install pip-only dependencies
        run: pip3 install pipreqs
      - name: Generate artifacts
        run: |
          export PATH=$PATH:~/.local/bin
          make dist NO_CYTHON=y VERSION=${{ steps.tag_name.outputs.tag }}
      - name: Attach artifacts to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adjust-keys.zip

