on:
  release:
    types:
      - created
name: Generate artifacts
jobs:
  generate-artifacts:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Get current tag
        uses: olegtarasov/get-tag@v2
        id: tag_name
      - name: Install dependencies
        run: sudo apt-get install -y pandoc help2man cython3
      - name: Install pip-only dependencies
        run: pip3 install pipreqs
      - name: Generate artifacts
        run: make dist VERSION=${{ steps.tag_name.outputs.tag }}
      - name: Attach artifacts to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adjust-keys.zip

