on:
  release:
    types:
      - created
name: Distributable generator
jobs:
  generate-distributables:
    name: Generate distributables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Generate artifacts
        run: make dist NO_CYTHON=y
      - name: Attach artifacts to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: adjust-keys.zip

